version: "3"

services:
        flaskapp:
                build: ./flaskapp-docker
                ports:
                        - "80:8000"
                volumes:
                        - ./data:/opt/data

                
