# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-flask:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build-And-Push-Flask-Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: smsubhan/flaskapp
          dockerfile: flaskapp-docker/Dockerfile
          tags: latest
  build-and-deploy-nginx:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build-And-Push-Flask-Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: smsubhan/nginx
          dockerfile: nginx/Dockerfile
          tags: latest
          
          
          image: docker-hub-repo/image-name
          -registry: docker.io
          -username: ${{ secrets.DOCKER_USERNAME }}
          -password: ${{ secrets.DOCKER_PASSWORD }}
