# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-flask:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - run: git lfs pull
    - name: Build-And-Push-Flask-Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: smsubhan/flaskapp
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          dockerfile: flaskapp-docker/Dockerfile
          directory: flaskapp-docker
          tags: latest
  build-and-deploy-nginx:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - run: git lfs pull
    - name: Build-And-Push-Flask-Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: smsubhan/nginx
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          dockerfile: nginx/Dockerfile
          directory: nginx
          tags: latest
